GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamBlur7iOS7
CamBlur7iOS7_FILES = Tweak.xm ../CKCB7BlurView.m
CamBlur7iOS7_FRAMEWORKS = CoreGraphics UIKit
CamBlur7iOS7_PRIVATE_FRAMEWORKS = QuartzCore
CamBlur7iOS7_INSTALL_PATH = /Library/Application Support/CamBlur7

include $(THEOS_MAKE_PATH)/library.mk
